---
abstract: 'Installs all number to word modules.'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  Test::More: 0.40
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Lingua-Any-Numbers
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Task::Lingua::Any::Numbers:
    file: lib/Task/Lingua/Any/Numbers.pm
    version: 0.17
requires:
  Lingua::AF::Numbers: 0
  Lingua::Any::Numbers: 0.41
  Lingua::BG::Numbers: 0
  Lingua::CS::Num2Word: 0
  Lingua::DE::Num2Word: 0
  Lingua::EN::Numbers: 0
  Lingua::ES::Numeros: 0
  Lingua::EU::Numbers: 0
  Lingua::FR::Numbers: 0
  Lingua::HU::Numbers: 0
  Lingua::ID::Nums2Words: 0
  Lingua::IT::Numbers: 0
  Lingua::JA::Numbers: 0
  Lingua::NL::Numbers: 0
  Lingua::NO::Num2Word: 0
  Lingua::PL::Numbers: 0
  Lingua::PT::Nums2Ords: 0
  Lingua::PT::Nums2Words: 0
  Lingua::SV::Numbers: 0
  Lingua::TR::Numbers: 0
  Lingua::ZH::Numbers: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-task-lingua-any-numbers/
version: 0.17
